//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMasterPage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public int IdPersonal { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public int Dni { get; set; }
        public Nullable<int> CentroDeCosto { get; set; }
        public Nullable<int> Localidad { get; set; }
        public bool Baja { get; set; }
    
        public virtual CentroCosto CentroCosto { get; set; }
        public virtual Localidades Localidades { get; set; }
    }
}
